### ISSUE TITLE
Design a splash screen for Quotes App

### ISSUE THREAD

**Issue by parjanya-rajput** [MSTC-DA-IICT/Hacktoberfest24-Quotes-App-Android#1]
The application features the view for different Quotes with author's name, design a splash screen which will be shown when the app is opened

**Comment by indra057** [comment]
can u assign me this issue

**Comment by parjanya-rajput** [comment]
I have assigned you one issue you need to complete that first

**Comment by piyushs-05** [comment]
@parjanya-rajput Can I take this issue as I have already completed the previous one

**Comment by indra057** [comment]
@parjanya-rajput i asked first so technically i should get it and also i finished the previous pr but it depends on the maintainer

**Comment by parjanya-rajput** [comment]
Sorry to inform that this issue will not be assigned to any one of you! As you both have completed one issues now will look for the other contributors. Thank you

**Comment by TERRA2k5** [comment]
@parjanya-rajput Can you assign this issue to me ?

**Comment by viratde** [comment]
@parjanya-rajput I would love to work on this issue. It would be great if you can assign this issue to me
