### ISSUE TITLE
Create a list-item to display quotes

### ISSUE THREAD

**Issue by parjanya-rajput** [MSTC-DA-IICT/Hacktoberfest24-Quotes-App-Android#2]
We will shift to API later, but for time being naviagate to main/java/com/example/quotesapp/assets folder there you will get a json file name quotes.json. To display it in the HomeScreen with each item having the quotes in bold letters and the author name below it we need a list item. 
**So your task is to design a list item that can be used in lazy column to display quotes and name the file as QuoteListItem**

**Comment by PrakashIrom** [comment]
Hi @parjanya-rajput I am interested in this task please assign it to me.

**Comment by parjanya-rajput** [comment]
I am assigning it to you! Hope you enjoy doing it!

**Comment by parjanya-rajput** [comment]
Good job
