### ISSUE TITLE
Display Quotes using the QuoteListItem

### ISSUE THREAD

**Issue by parjanya-rajput** [MSTC-DA-IICT/Hacktoberfest24-Quotes-App-Android#3]
If QuoteListItem is not available then make one an navigate to assets folder there you will find json file containing all quotes display in HomeScreen. If QuoteListItem is available use it as item in LazyColumn.
- Quotes are read from QuotesManagerViewModel or simply QuotesManager so use that file accordingly (if it's empty a bonus issue will be available of reading an parsing a json file so look for it in issues section)

**Comment by piyushs-05** [comment]
Hey i would like to take the issue and do the task

**Comment by parjanya-rajput** [comment]
I am assigning you this issue! Enjoy working on it

**Comment by piyushs-05** [comment]
Thanks for the opportunity, I will update you on it asap

**Comment by piyushs-05** [comment]
@parjanya-rajput I have created a pull request regarding the issue , please review it

**Comment by parjanya-rajput** [comment]
PR looks fine and everything is up and running!
