### ISSUE TITLE
Design a QuoteDetailView

### ISSUE THREAD

**Issue by parjanya-rajput** [MSTC-DA-IICT/Hacktoberfest24-Quotes-App-Android#4]
Design a Card View which will show the Quote in more beautiful and highlighted way and the author name below it.

**Comment by indra057** [comment]
1.can u assign me this issue...
2.should i create a specific card view where the quotes when clicked(from the lazy column list) show only the clicked quote along with the author in more beautiful and highlighted way if yes then i can proceed otherwise can u please describe in more specific way

**Comment by parjanya-rajput** [comment]
I am assigning you this issue once you do this I will assign another on which you've commented!
should i create a specific card view where the quotes when clicked(from the lazy column list) show only the clicked quote along with the author in more beautiful and highlighted way if yes then i can proceed otherwise can u please describe in more specific way - Yes similar to this but as of now you just have to implement the design part click function is not required so just create a cardview once the Quotes are displayed then new issue will be raised for the same

**Comment by indra057** [comment]
@parjanya-rajput sir i have created a QuoteDetailScreen that will take some input string of quote and input string of author (or from the lazycolumn or the viewmodel) and  then display in a card ....is it okk or should i implement or change something else before give pull request as this part comes under design ..
![Screenshot 2024-10-05 185752](https://github.com/user-attachments/assets/04e5fb49-c5ab-4fb2-aca1-43c4ee75f5a9)

**Comment by parjanya-rajput** [comment]
For now just a keep a simple static string no need to take input or create viewModel. 
Design looks neat! Good job

**Comment by indra057** [comment]
@parjanya-rajput sir can i submit a pr regarding this with input of quote as a static string and input of output as another static string

**Comment by parjanya-rajput** [comment]
Yes
