### ISSUE TITLE
Read Quotes from assets/quotes.json

### ISSUE THREAD

**Issue by parjanya-rajput** [MSTC-DA-IICT/Hacktoberfest24-Quotes-App-Android#5]
- In QuoteManager file write a code that will read and parse the quotes.json file given in assets folder and return an array of type quote.kt (model/quote.kt) 
- Also add a boolean check if the parsing is completed an returning array is not null

**Comment by indra057** [comment]
can u please assign me this issue

**Comment by parjanya-rajput** [comment]
This issue is now solved!
